### PR TITLE
adding_airspyhf_to_cubicsdr

### PR DESCRIPTION
**Pull request by Brumi-2021**
Hello,  congrat for this maintenance of cubicsdr to gentoo.!!!!
It is also a great SDR program ! 
 
BTW , Recently , I do not see your repo in the official  eselect repository list ,   maybe it is my settings mistake .
I am running a pentoo linux system. But I am totally newbie about gentoo ebuilds. 

A few days ago , I managed to modify your original cubicsdr  ebuild  locally ,  adding airspyhf , 
image

Cubicsdr  		→ modifyed local ebuild copy of stefan’s  : net-wireless/cubicsdr-0.2.7-r1
     Soapysdr		→ modifyed local ebuild copy of gentoo  net-wireless/soapysdr-0.8.1-r1
           Soapyairspyhf.  → generated new local ebuilt  net-wireless/soapyairspyhf-0.2.0  Soapy sdr module)

           Soapyhackrf     (other , exisiting Soapy  sdr modules)
           Soapyrtlsdr       (other , exisiting Soapy  sdr modules)
           soapyplutosdr

But today , I deleted cubicsdr , then  updated my system and now , when trying to re-install again , I can see conflicts, about 
x11-libs/wxGTK:3.2-gtk3

I would appreciate if you can continue updating it .and solving those conflicts. 
image

Feel free to cancel that PR , or modify it ,  to improve it .
BTW ,  in the new ebuld soapyairspyhf , tentativelly I also added your email in the metadata.
Maybe the easy way would be to create new name versions of those ebuilds to avoid collisions ?  (but I am still not familiar about how to do it , and solve all conflicts, 

Thanks,  cheers.

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Thanks! I'll take a look.

> BTW , Recently , I do not see your repo in the official eselect repository list 

Using app-eselect/eselect-repository-14:

```bash
# eselect repository list | grep stefantalpalaru
  [336] stefantalpalaru @
# grep REMOTE_LIST_URI /etc/eselect/repository.conf
REMOTE_LIST_URI=https://qa-reports.gentoo.org/output/repos/repositories.xml
```

And the wxGTK version in my overlay is "3.2.6-r300".

**Comment by Brumi-2021** [comment]
Hi thanks for your quick reply .
I still do not see you in my eselect  repository list , 
In the past I had it activated , but when I started to play locally , I switched disabling to avoid conflicts, but now I can now enable it or see you , 

sudo eselect repository enable stefantalpalaru
--2024-09-28 16:13:35--  https://qa-reports.gentoo.org/output/repos/repositories.xml
Resolving qa-reports.gentoo.org... 151.101.133.91, 2a04:4e42:1f::347
Connecting to qa-reports.gentoo.org|151.101.133.91|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘/root/.cache/eselect-repo/repositories.xml’ not modified on server. Omitting download.

No reply at all about , eselect repository list | grep stefantalpalaru

Maybe I need to resync or update my list , ???

image

I will continue investigating about it .

**Comment by stefantalpalaru** [comment]
Those fuckers actually removed my overlay from the list :-)  https://github.com/gentoo/api-gentoo-org/commit/7c46900a7c4cd57b11091ae8327a1e855bb97762
They're as petty as they are incompetent...

Try: `eselect repository add stefantalpalaru git https://github.com/stefantalpalaru/gentoo-overlay`

**Comment by Brumi-2021** [comment]
Hi,  yeahh ,  
I also could not see your repo in some official  gentoo repo web . But now is clear , 
Now it worked , I could also see  your repo again , but it appears with "@" , like my local repo. 
  [337] steam-overlay (https://github.com/anyc/steam-overlay)
  [338] stefantalpalaru @
  [339] stephdewit (https://github.com/stephdewit/gentoo-overlay)

Thanks,

**Comment by stefantalpalaru** [comment]
Merged in: https://github.com/stefantalpalaru/gentoo-overlay/commit/5d0e9b7fbed83a82ad847b4b9c1a1d15702e9aee

Thanks!

**Comment by Brumi-2021** [comment]
Thanks !
I see, you created r2 , good !
I am trying to emerge again cubicsdr to test it , but so far , I am getting conflicts, 
I will keep investigating it . 
image
As soon as I can confirm it , I will let you know ,

**Comment by stefantalpalaru** [comment]
You also need to upgrade soapysdr.

**Comment by Brumi-2021** [comment]
Yes , trying , but always emerge the r1 , not your r2 ,..
image

**Comment by stefantalpalaru** [comment]
Try: `emerge -pv soapysdr::stefantalpalaru` to see what's the error.

**Comment by Brumi-2021** [comment]
emerge -pv soapysdr::stefantalpalaru . :

image

Not sure what it means , 
    (no parents that aren't satisfied by other packages in this slot)

   This dependency graph of each one , seems correct 
image

And equery d soapysdr 
image

**Comment by stefantalpalaru** [comment]
Try uninstalling it first: `emerge -C soapysdr; emerge -1 soapysdr`

**Comment by Brumi-2021** [comment]
Thanks for your help !

Uninstalling first , worked !!!!
Then I could emerge your soapysdr , and cubicsdr .  
And it works perfect !!!!! 
But it is strange , the USE flag of airspyhf is off , but now it detects correctly the airspyhf , (same as yesterday with my local ebuild ,) 
image

Strange but it works well !!!!  Thanks a lot 
image

**Comment by stefantalpalaru** [comment]
You must have "soapyairspyhf" installed explicitly. The USE flag only adds that dependency.

**Comment by Brumi-2021** [comment]
Hello , 
yeah , I think that I installed "soapyairspyhf"  explicitly , directly by me in my local build testing  , not pulled by dependencies in soapysdr emerge.
Moreover, checking soapysdr use flags, similar , 

I can see same , 
image

Ok, thanks for clarifying it .

By the way , 
Just from terminal -when plugged  , when checking 
airspyhf_info ---> as before , it detects correctly 
hackrf_info --> same 
rtl_test -->  and stop it with CTRL-C ,

image

Anyway , NOW , the SoapySDRUtil  also detects the 3 x sdr's types that I have , including  airspyhf !!!!! 
SoapySDRUtil --probe="driver=rtlsdr"
SoapySDRUtil --probe="driver=hackrf"
SoapySDRUtil --probe="driver=airspyhf"
SoapySDRUtil --probe="driver=airspyhf"

image


qspectrumanalyzer also detects it , but I never used before , when pressing start button, I got some other error .(maybe just setting issue) 
Checking SoapySDR ecosystem graph , now I better understand why GQRX and GNURADIO already worked well with my airspyhf , with special gr-osmosdr version (from sattvik repo) .

image

**Comment by Brumi-2021** [comment]
Hi , I also shared that PR ,  link to the pentoo overlay github community ,  
because based on soapysdr metadata , if he feels intersting it , he might update and maintain the official  gentoo soapysdr ebuild version . 

Cheers,

**Pull request closed without merging**
